@startuml
hide footbox

actor "Security Operator" as SecurityOperator
participant "kubelet" as Kubelet
participant Pod [
  =Pod
  ----
  ""-Vault Agent (init container)""
  ""-Secure Photo Hub (container)""
]
participant "Vault HashiCorp" as Vault


== Pod Deployment ==
SecurityOperator -> Kubelet: 0. Deploy Pod (kubectl apply)
Kubelet -> Pod: 1. Create Pod with two containers
Kubelet -> Pod: 1.1 Create JWT and store it in the Pod (env var)

== Authentication ==
Pod -> Vault: 2. Send JWT to Vault for authentication
Vault -> Kubelet: 3. Invoke TokenReviewAPI (authentication)
note right: TokenReview tenta di autenticare un token a un utente conosciuto.
Kubelet -> Vault: 4. Respond with Service Account Names / Namespaces
Vault -> Vault: 5. Verify: Service Account / Namespace matched against policy
note right
Verifica se l'utente ha
l'autorizzazione ad
accedere ai secrets
end note

Vault -> Pod: 6. Return Vault Auth Token

@enduml