apiVersion: v1
kind: Pod
metadata:
  name: secure-photo-hub-with-vault-agent-pod
  namespace: default
spec:
  serviceAccountName: vault-auth

  volumes:
    - configMap:
        items:
          - key: vault-agent-config.hcl
            path: vault-agent-config.hcl
        name: example-vault-agent-config
      name: config
    - configMap:
        items:
          - key: application-properties.yaml
            path: application-properties.yaml
        name: secure-photo-hub-configmap
      name: secure-photo-hub-configmap
    - emptyDir: {}
      name: shared-data

  initContainers:
    - args:
        - agent
        - -config=/etc/vault/vault-agent-config.hcl
        - -log-level=debug
      env:
        - name: VAULT_ADDR
          value: http://dockerhost:8200
      image: hashicorp/vault
      name: vault-agent
      volumeMounts:
        - mountPath: /etc/vault
          name: config
        - mountPath: /etc/secrets
          name: shared-data

  containers:
    - image: localhost:5001/secure-photo-hub
      name: secure-photo-hub
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /config/application-properties.yaml
          name: secure-photo-hub-configmap
          subPath: application-properties.yaml
        - mountPath: /secrets/application-secrets.yaml
          name: shared-data
          subPath: application-secrets.yaml
      env:
        - name: CONFIG_LOCATION
          value: /config/application-properties.yaml
        - name: SECRETS_LOCATION
          value: /secrets/application-secrets.yaml