apiVersion: v1
data:
  vault-agent-config.hcl: |
    exit_after_auth = true

    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "secure-photo-hub-role"
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }

    template {
    destination = "/etc/secrets/application-secrets.yaml"
    contents = <<EOT
    {{- with secret "secure-photo-hub/data/application-secrets" }}
    {{ .Data.data.yaml }}
    {{ end }}
    EOT
    }


kind: ConfigMap
metadata:
  name: example-vault-agent-config
  namespace: default